// Curated demonstration experiences. Prices, availability and travel times are estimates.
export const activities=[
 {id:'riverside',title:'沿着西岸，把风景慢慢看',category:'walk',label:'城市漫步',area:'徐汇 · 西岸滨江',price:0,minutes:60,indoor:false,img:'park',tags:['摄影','散步','放空'],description:'沿江走一段不赶时间的路，看看来往的骑行者，在喜欢的光线里停下来。适合两个人边走边聊，也适合独自戴上耳机。',tip:'推荐下午出发；遇雨可换成附近的室内展览。步道无需门票，交通另计。',meet:'西岸滨江公共步道入口',accent:'一段不用买票的好时光'},
 {id:'gallery',title:'给自己一场看展的时间',category:'art',label:'看个展',area:'徐汇 · 西岸艺术片区',price:40,minutes:70,indoor:true,img:'gallery',tags:['艺术','摄影','室内'],description:'用一个小时认真看一场展，挑出你最喜欢的作品，和朋友交换看法。这里是一份看展灵感，具体展览与票价请出发前查询场馆公告。',tip:'票价为示例估算，实际展览可能需要预约。图片为艺术展厅氛围参考。',meet:'西岸艺术片区场馆入口',accent:'雨天也能走进好风景'},
 {id:'coffee',title:'咖啡和一本没读完的书',category:'shop',label:'逛逛小店',area:'徐汇 · 龙腾大道周边',price:28,minutes:50,indoor:true,img:'coffee',tags:['咖啡','阅读','室内'],description:'找一张靠窗的桌子，把手机暂时收起来。用一杯咖啡的时间，读几页书，或者聊聊最近的小事。',tip:'预计 ¥28 为一杯饮品预算，不含正餐；具体店铺与营业时间需出发前确认。',meet:'龙腾大道周边咖啡店',accent:'为周末留一点空白'},
 {id:'bookstore',title:'在书架之间，偶遇新世界',category:'shop',label:'逛逛小店',area:'徐汇 · 滨江书店空间',price:0,minutes:45,indoor:true,img:'coffee',tags:['阅读','安静','室内'],description:'给自己一个小任务：选一本从没读过的题材，读完第一章。逛书店不一定要买书，好奇心就是入场券。',tip:'公共阅读区以店内规则为准；饮品和购书费用自选，不计入免费体验。',meet:'滨江片区书店入口',accent:'零元也能收获灵感'},
 {id:'photo',title:'带上相机，收集城市切片',category:'walk',label:'城市漫步',area:'徐汇 · 滨江建筑群',price:0,minutes:55,indoor:false,img:'park',tags:['摄影','建筑','散步'],description:'寻找建筑的线条、树影和街角的颜色。不必拥有专业设备，一部手机也可以记录城市的另一面。',tip:'推荐舒适鞋履；请勿进入非开放建筑区域。雨天推荐切换室内计划。',meet:'滨江开放公共广场',accent:'手机也能拍出周末大片'},
 {id:'market',title:'去小市集，淘一点喜欢',category:'market',label:'周末市集',area:'徐汇 · 艺术街区',price:15,minutes:55,indoor:false,img:'coffee',tags:['手作','市集','社交'],description:'看看手作摊位、独立设计和旧物，听摊主讲一件小东西的故事。这是市集场景示例，不代表当前有正在举办的活动。',tip:'¥15 为小额消费预留；活动日期与是否开放请查询主办方信息。',meet:'艺术街区公共广场',accent:'遇见一点意料之外'},
 {id:'vinyl',title:'在唱片里，听见一个下午',category:'music',label:'音乐角落',area:'徐汇 · 艺术街区',price:20,minutes:50,indoor:true,img:'coffee',tags:['音乐','复古','室内'],description:'从一张不熟悉的唱片开始，找到今天的背景音乐。适合朋友一起试听、交换歌单，或者安静地待一会儿。',tip:'¥20 为店内消费预留；试听与营业规则以所选店铺为准。',meet:'艺术街区唱片店',accent:'给周末换一张播放列表'},
 {id:'green',title:'在城市绿地，短暂离线',category:'nature',label:'亲近自然',area:'徐汇 · 滨江公共绿地',price:0,minutes:60,indoor:false,img:'park',tags:['自然','放空','散步'],description:'沿开放绿地散步，在树下坐一会儿。无需复杂装备，把行程放慢，给眼睛和思绪一点休息。',tip:'建议自带水；遵守绿地开放规则。不安排野外或夜间徒步。',meet:'滨江公共绿地入口',accent:'把电量充在阳光里'},
 {id:'studio',title:'把喜欢的颜色，留在纸上',category:'art',label:'艺术体验',area:'徐汇 · 艺术街区',price:58,minutes:80,indoor:true,img:'gallery',tags:['艺术','手作','室内'],description:'用简单材料完成一张属于周末的画。不追求画得像，只记录你今天看到的颜色和心情。',tip:'¥58 为体验课示例预算；是否开课、材料和名额需向工作室确认。',meet:'艺术街区工作室',accent:'让周末有一件带得走的作品'}
];
export const categories=[['all','compass','全部灵感'],['art','art','看个展'],['walk','walk','城市漫步'],['shop','coffee','逛逛小店'],['market','users','周末市集'],['music','music','听点音乐'],['nature','leaf','亲近自然']];
export const sampleTeams=[{id:'demo1',title:'周六西岸散步，边走边拍',host:'小林',initial:'林',style:'green',members:2,capacity:4,time:'周六 13:00',place:'西岸滨江公共步道入口',description:'不用专业相机，手机也欢迎。走累了就找家小店坐坐。',tags:['摄影搭子','轻松不赶路'],route:['riverside','gallery','bookstore']},{id:'demo2',title:'下雨也出门：看展＋书店',host:'阿橙',initial:'橙',style:'orange',members:1,capacity:3,time:'周日 14:00',place:'西岸艺术片区场馆入口',description:'一起看展，再交换一本最近喜欢的书。慢热友好。',tags:['看展搭子','室内计划'],route:['gallery','bookstore']},{id:'demo3',title:'预算 50 元的城市放空计划',host:'小满',initial:'满',style:'blue',members:3,capacity:5,time:'周六 14:30',place:'滨江公共绿地入口',description:'去绿地晒会儿太阳，沿江散散步。带一瓶水就好。',tags:['低预算','自然充电'],route:['green','riverside']}];
