// Real places. Checked = source consulted, not an on-site check or live availability.
export const checkedAt='2026-10-04';
const artSource='https://whlyj.sh.gov.cn/msg/20250928/db0cbc0a1edf478f99c4900522a56e3b.html';
const districtSource='https://ghzyj.sh.gov.cn/xh/20230907/4507797618a846c8b918395de603cfaa.html';
const originBase='http://www.xujiahuiorigin.com/zouJin/inner?columnId=d4f0f2448e2a0cabbed64fb2d25cbf94&id=';
export const activities=[
 {id:'xujiahui-park',title:'徐家汇公园 · 给心情放个假',category:'nature',label:'公园放空',area:'徐汇 · 徐家汇',address:'肇嘉浜路889号',price:0,minutes:45,indoor:false,img:'park',tags:['公共绿地','散步','自带水'],description:'在真实的城市公共绿地里慢慢走，不追求打卡数量。找一处可以休息的位置，让这次出门先从放松开始。',tip:'开放式公共绿地，方案只包含散步；具体开放时段与临时管制未核实，按现场公示。园内消费自选。',meet:'徐家汇公园肇嘉浜路889号入口外',accent:'不用消费，也能拥有一个下午',hours:null,closedDays:[],opening:'开放时段待确认 · 建议白天游览',booking:'公共绿地散步；按现场开放与管理规则',source:districtSource,sourceName:'上海市规划和自然资源局',priceNote:'公共绿地散步不含收费服务',check:'确认公园当天可进入，带好水和舒适鞋'},
 {id:'wukang-building',title:'武康大楼 · 街角看建筑',category:'walk',label:'街区漫步',area:'徐汇 · 衡复片区',address:'武康路与淮海中路交会处',price:0,minutes:30,indoor:false,img:'park',tags:['建筑外观','街区','手机摄影'],description:'从公共街道欣赏武康大楼外观，观察建筑线条和街区生活。这里安排的是街角漫步，不是进入住宅内部参观。',tip:'住宅建筑仅看外观；在人行道停留，避开车流，不堵门口。假日客流可能影响步行与拍照时间。',meet:'武康路与淮海中路交会处公共人行道',accent:'留意街角，不必追逐打卡机位',hours:null,closedDays:[],opening:'公共街道外观 · 建议白天游览',booking:'仅外观，无建筑内部参观名额',source:'https://whlyj.sh.gov.cn/wbzx/20220627/ca2550ff9a7c4646b58668e4bec959c4.html',sourceName:'上海市文化和旅游局',priceNote:'公共街道看外观，不含探店消费',check:'确认街区通行情况，仅在人行道看外观'},
 {id:'xuhui-art',title:'徐汇区艺术馆 · 慢慢看一场展',category:'art',label:'免费文化场馆',area:'徐汇 · 衡复片区',address:'淮海中路1413号',price:0,minutes:45,indoor:true,img:'gallery',tags:['艺术','室内','免费场馆'],description:'给作品留一点时间，也给同行的人留一点讨论空间。推荐的是艺术馆场所；当期展览内容和换展安排需要另行确认。',tip:'官方名录列为免费。周一常规闭馆，节假日及布展安排可能调整。未核实当天展览和预约规则。',meet:'徐汇区艺术馆淮海中路1413号入口外',accent:'室内文化空间，转场仍需带伞',hours:{open:540,close:1020,last:990},closedDays:[1],opening:'周二至周日 09:00—17:00，16:30停止入场',booking:'预约及换展状态待确认',source:artSource,sourceName:'上海市文旅局 · 2025美术馆名录',priceNote:'名录列为免费；特殊活动另行核对',check:'确认当天有展览开放，核对预约/换展公告'},
 {id:'painting-museum',title:'上海中国画院美术馆 · 看笔墨与留白',category:'art',label:'免费文化场馆',area:'徐汇 · 衡复片区',address:'岳阳路197号',price:0,minutes:45,indoor:true,img:'gallery',tags:['中国画','室内','安静看展'],description:'放慢节奏，在笔墨与留白之间找一幅喜欢的作品。场馆真实存在；当前展览、临时闭馆和预约情况以公告为准。',tip:'官方名录列为免费，常规周二至周日开放。假期或换展可能调整，出发前核对。',meet:'上海中国画院美术馆岳阳路197号入口外',accent:'两个人可以各选一幅喜欢的作品',hours:{open:570,close:990},closedDays:[1],opening:'周二至周日 09:30—16:30',booking:'预约及换展状态待确认',source:artSource,sourceName:'上海市文旅局 · 2025美术馆名录',priceNote:'名录列为免费；特殊活动另行核对',check:'确认当天开放与当前展览，核对预约要求'},
 {id:'tushanwan',title:'土山湾博物馆 · 发现城市的另一面',category:'art',label:'免费博物馆',area:'徐汇 · 徐家汇',address:'蒲汇塘路55号',price:0,minutes:50,indoor:true,img:'gallery',tags:['城市历史','室内','免费参观'],description:'看看土山湾的工艺与中西文化交流故事。和朋友各找一件印象深的展品，离开后交换自己的发现。',tip:'景区官网列为免费参观。常规周一闭馆，16:00停止入场；节假日安排另行确认。',meet:'土山湾博物馆蒲汇塘路55号入口外',accent:'用一件展品，打开一段城市故事',hours:{open:540,close:990,last:960},closedDays:[1],opening:'周二至周日 09:00—16:30，16:00停止入场',booking:'临时开放调整与预约要求待确认',source:originBase+'2b51876f064beceff096b737376cad1e',sourceName:'徐家汇源景区官网',priceNote:'景区官网列为免费参观',check:'确认博物馆开放/预约要求，16:00前入场'},
 {id:'xujiahui-library',title:'徐家汇书院 · 各自挑一本书',category:'shop',label:'公共阅读空间',area:'徐汇 · 徐家汇',address:'漕溪北路158号',price:0,minutes:45,indoor:true,img:'coffee',tags:['阅读','室内','朋友同行'],description:'在公共阅读空间各自挑一本感兴趣的书，再交流一段印象深的内容。当日开放区域与活动规则需先确认。',tip:'文旅推广页列为免费、无需预约。周一馆休，法定假日及特定活动规则另行公告；不含咖啡、文创或购书。',meet:'徐家汇书院漕溪北路158号入口外',accent:'把时间留给阅读，也留给朋友',hours:{open:540,close:1260,last:1230},closedDays:[1],opening:'周二至周日 09:00—21:00，20:30停止入馆',booking:'文旅推广页列为无需预约；假日/活动规则需核对',source:'https://www.meet-in-shanghai.net/cn/guide/xujiahuiyuan-city-walk-611364/',sourceName:'上海市文旅推广网',priceNote:'文旅推广页列为免费公共阅读；消费自选',check:'确认书院当天开放区域与假日/活动安排'},
 {id:'film-museum',title:'上海电影博物馆 · 走进光影故事',category:'art',label:'收费博物馆',area:'徐汇 · 徐家汇',address:'漕溪北路595号',price:60,minutes:90,indoor:true,img:'gallery',tags:['电影','室内','收费体验'],description:'看电影如何从幕后走到银幕，留出更完整的参观时间。推荐常设场馆，不包含电影放映或特别活动。',tip:'景区官网列成人票60元，优惠资格与当天票价请通过场馆官方渠道核对。本方案按成人票预留，不默认所有学生都能使用优惠票。',meet:'上海电影博物馆漕溪北路595号入口外',accent:'愿意多留一点预算，换一段光影体验',hours:{open:570,close:990,last:960},closedDays:[1],opening:'景区页列周二至周日09:30—16:30，16:00停止入场',booking:'官方购票渠道、优惠资格与假日开放待核对',source:originBase+'c4fd0a78937c3626e8136bd3b9876bd3',sourceName:'徐家汇源景区官网',priceNote:'公开成人票60元；学生优惠须另核对',check:'核对电影博物馆当天开放、票价与购票要求'}
];
export const categories=[['all','compass','全部去处'],['nature','leaf','公园放空'],['walk','walk','街区漫步'],['art','art','看展逛馆'],['shop','book','安静阅读']];
export const routeOptions=[
 {id:'slow',title:'小预算，给心情放个假',subtitle:'公园放空 × 街角建筑',ids:['xujiahui-park','wukang-building'],tone:'green',icon:'leaf',scene:'晴天 · 一个人也自在',strength:'适中 · 街区步行',reason:'两站公共空间，把钱留给餐饮和来回交通。',caution:'公园开放时段待确认；只看建筑外观。'},
 {id:'rain',title:'下雨也有一个好下午',subtitle:'徐汇艺术馆 × 中国画院',ids:['xuhui-art','painting-museum'],tone:'blue',icon:'rain',scene:'雨天 · 两站室内',strength:'轻松 · 转场需要带伞',reason:'室内停留为主，免费文化场馆适合慢慢看。',caution:'须核对当天展览、换展和预约；周一常规闭馆。'},
 {id:'friends',title:'和朋友，各自带走一点发现',subtitle:'土山湾博物馆 × 徐家汇书院',ids:['tushanwan','xujiahui-library'],tone:'orange',icon:'users',scene:'朋友同行 · 雨天也可选',strength:'轻松 · 短途转场',reason:'先看城市故事，再各挑一本书，聊天更有话题。',caution:'书院周一馆休，假日与特定活动规则需确认。'},
 {id:'film',title:'多一点预算，走进光影故事',subtitle:'电影博物馆 × 徐家汇书院',ids:['film-museum','xujiahui-library'],tone:'orange',icon:'art',scene:'可选付费体验 · 按成人票预留',strength:'轻松 · 室内参观为主',reason:'为一场完整的电影文化参观多留一点时间与预算。',caution:'成人票公开价60元；学生优惠与当天购票须另核对。'}
];
export const sampleTeams=[
 {id:'demo1',title:'公园和街角，轻松走走',host:'小林',initial:'林',style:'green',members:2,capacity:4,time:'周六 13:00',place:'徐家汇公园肇嘉浜路889号入口外',description:'手机摄影也欢迎，先确认时间和费用，再一起出发。',tags:['熟人出发卡','示例队伍'],route:['xujiahui-park','wukang-building']},
 {id:'demo2',title:'下雨也出门：两处文化场馆',host:'阿橙',initial:'橙',style:'orange',members:1,capacity:3,time:'周日 13:00',place:'徐汇区艺术馆淮海中路1413号入口外',description:'慢慢看展，不赶场；需要提前核对当天开放与预约。',tags:['看展搭子','示例队伍'],route:['xuhui-art','painting-museum']},
 {id:'demo3',title:'博物馆和书院，交换一个发现',host:'小满',initial:'满',style:'blue',members:2,capacity:4,time:'周六 13:00',place:'土山湾博物馆蒲汇塘路55号入口外',description:'先确认书院当天开放，再一起安排这个下午。',tags:['文化漫游','示例队伍'],route:['tushanwan','xujiahui-library']}
];
export const campuses=[
 {id:'sjtu-xuhui',name:'上海交大 · 徐汇校区',address:'华山路1954号',reserve:30,method:'可先比较步行与公共交通',source:'https://gk.sjtu.edu.cn/Data/List/bxdd'},
 {id:'ecust-xuhui',name:'华东理工 · 徐汇校区',address:'梅陇路130号',reserve:45,method:'可先比较地铁 / 公交 + 步行',source:'https://www.ecust.edu.cn/2024/0620/c591a181592/page.htm'},
 {id:'shnu-xuhui',name:'上海师大 · 徐汇校区',address:'桂林路100号',reserve:45,method:'可先比较公共交通 + 步行',source:'https://psy.shnu.edu.cn/30425/list.htm'}
];
